#!/usr/bin/env node
import fs from "node:fs"; import os from "node:os"; import path from "node:path"; import readline from "node:readline"; import prompts from "prompts";
type C={provider:string,apiKey:string,model:string,baseUrl:string};
const d=path.join(os.homedir(),".config","teynex"), f=path.join(d,"config.json");
const load=():C|null=>{try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return null}};
const save=(c:C)=>{fs.mkdirSync(d,{recursive:true,mode:0o700});fs.writeFileSync(f,JSON.stringify(c,null,2),{mode:0o600})};
async function setup(){const p=await prompts([
{type:"select",name:"provider",message:"API provider",choices:[{title:"OpenRouter",value:"openrouter"},{title:"OpenAI",value:"openai"},{title:"Groq",value:"groq"},{title:"Gemini",value:"gemini"},{title:"Custom OpenAI-compatible",value:"custom"}]},
{type:"password",name:"apiKey",message:"API key"},
{type:"text",name:"model",message:"Model",initial:"openai/gpt-4o-mini"},
{type:"text",name:"baseUrl",message:"Base URL",initial:"https://openrouter.ai/api/v1"}]); if(p.apiKey&&p.model&&p.baseUrl){save(p);console.log("\n✓ API saved to ~/.config/teynex/config.json\n")}}
async function ask(c:C,q:string){const r=await fetch(c.baseUrl.replace(/\/$/,"")+"/chat/completions",{method:"POST",headers:{"content-type":"application/json","authorization":"Bearer "+c.apiKey},body:JSON.stringify({model:c.model,messages:[{role:"system",content:"You are Teynex AI, a concise coding assistant."},{role:"user",content:q}]})});const t=await r.text();if(!r.ok)throw Error("API "+r.status+": "+t.slice(0,500));return JSON.parse(t).choices?.[0]?.message?.content??t}
async function main(){const a=process.argv.slice(2);if(a[0]=="--version")return console.log("teynex 2.0.0");if(a[0]=="setup")return setup();let c=load();if(!c){console.log("Teynex first-run API setup");await setup();c=load();if(!c)return}if(a[0]=="config")return console.log(JSON.stringify({...c,apiKey:"***configured***"},null,2));if(a[0]=="doctor")return console.log("Node "+process.version+"\nProvider: "+c.provider+"\nModel: "+c.model);console.log("Teynex AI • "+c.provider+" • "+c.model);const rl=readline.createInterface({input:process.stdin,output:process.stdout,prompt:"› "});async function run(q:string){try{console.log("\n"+await ask(c!,q)+"\n")}catch(e){console.error("\n"+e+"\n")}}if(a.length){await run(a.join(" "));rl.close();return}console.log("Commands: /setup /config /doctor /exit");rl.prompt();rl.on("line",async x=>{x=x.trim();if(x=="/exit")return rl.close();if(x=="/setup"){await setup();c=load()!}else if(x=="/config")console.log(JSON.stringify({...c,apiKey:"***configured***"},null,2));else if(x=="/doctor")console.log("Node "+process.version+" • "+c!.provider+" • "+c!.model);else if(x)await run(x);rl.prompt()})}main();
